Java Examples for onnx and MNIST for TF
KonduitAI/konduit-serving-docs pull request #5
Opened 2020-01-27 04:49 UTC by venkat-nidrive

Java Example docs created for illustrate the konduit serving framework for model step and python step in onnx and mnist.

document for bert is moved to subfolder to make same level as mnist.

2020-01-27 09:17 UTC, ShamsUlAzeem requested changes
Make sure you update the summary.md file like I've done here: https://github.com/KonduitAI/konduit-serving-docs/pull/6/files so the newly added files are picked up by gitbook

2020-01-27 09:17 UTC, ShamsUlAzeem commented
@venkat-nidrive a few changes to do here. I've left comments

2020-01-28 03:52 UTC, venkat-nidrive commented
> Make sure you update the summary.md file like I've done here: https://github.com/KonduitAI/konduit-serving-docs/pull/6/files so the newly added files are picked up by gitbook

Updated summary.md file with latest java examples .

2020-01-28 10:23 UTC, ShamsUlAzeem requested changes
@venkat-nidrive minor nits

2020-01-28 10:23 UTC, ShamsUlAzeem commented on examples/java/dl4j_java.md
> +  This documents illustrates how to create Konduit Serving configurations with the Java SDK:
typo: should be `This document`

2020-01-28 10:54 UTC, venkat-nidrive commented on examples/java/dl4j_java.md
> +  This documents illustrates how to create Konduit Serving configurations with the Java SDK:
Typo issue fixed.

2020-01-29 10:53 UTC, merged